services:
  api:
    build: ./apps/api
    container_name: 9nau-api
    networks:
      - nau-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:16
    container_name: 9nau-postgres
    networks:
      - nau-network
    volumes:
      - 9nau-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: 9nau-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - nau-network
    restart: unless-stopped

networks:
  nau-network:
    external: true

volumes:
  9nau-postgres-data:
