services:
  api:
    build: ./apps/api
    container_name: 9nau-api
    networks:
      - nau-network
    depends_on:
      - 9nau_postgres
      - 9nau_redis
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 192M

  9nau_postgres:
    image: postgres:16
    container_name: 9nau-postgres
    networks:
      - nau-network
    volumes:
      - 9nau-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 192M

  9nau_redis:
    image: redis:7-alpine
    container_name: 9nau-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - nau-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 192M

networks:
  nau-network:
    external: true

volumes:
  9nau-postgres-data:
